import type { Metadata } from "next"
import { Brygada_1918, Inter, JetBrains_Mono } from "next/font/google"
import "@/app/globals.css"
import { auth } from "@/auth"
import SignOut from "@/app/components/sign-out"
import SignIn from "@/app/components/sign-in"
import { ThemeProvider } from "@/app/components/theme-provider"
import { ThemeToggle } from "@/app/components/theme-toggle"
import UserProfileBadge from "@/app/components/user-profile-badge"

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["cyrillic", "latin"],
})

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["cyrillic", "latin"],
})

const brygadaSerif = Brygada_1918({
  variable: "--font-brygada-serif",
  subsets: ["cyrillic", "latin"],
})

export const metadata: Metadata = {
  title: "Mini blog",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await auth()

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} ${brygadaSerif.variable} antialiased min-h-dvh flex flex-col`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem enableColorScheme>
          <header className="flex items-center p-2 gap-2 sticky top-0 justify-end backdrop-blur-xs bg-background/80">
            {session && <UserProfileBadge session={session} />}
            {session?.user ? <SignOut /> : <SignIn />}
            <ThemeToggle />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
